### ISSUE TITLE
CLI tool print last 7 days stats

### ISSUE THREAD

**Issue by tonytony2020** [giant-stone/gmq#4]
https://github.com/giant-stone/gmq/blob/master/gmq/cmd/gmqcli/main.go#L40
cmdStatsWeekly 合并入 cmdPrintStats

**Comment by tonytony2020** [comment]
bc7ee18b6e781c8a35aeee6dc82a01453955aa94

**Comment by tonytony2020** [comment]
v0.0.10 中 gmqcli -week 输出 processed failed 两列数据对调统计有误

**Comment by CDoutzen** [comment]
提交[e5d4a2a](https://github.com/giant-stone/gmq/pull/12/commits/e5d4a2abe8950266506ed2325fcd071ce5c76454)
